access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVVVJRCI6IjVlOTkwMmM5LTdiNGEtNDE5OS1hYTA1LTJjYTljYjMyNjQ1ZCIsImlzcyI6ImJvb3QuZGV2IiwiZXhwIjoxNzcyOTE0MDYyLCJpYXQiOjE3NzI5MTA0NjJ9.aQHs8EWuD7HY-e6jaFEEYck-Atz_rAU7eMGnRH2l5Ec
api_url: https://api.boot.dev
color:
    gray: "8"
    green: "2"
    red: "1"
frontend_url: https://boot.dev
last_refresh: 1772910462
refresh_token: nvE7hXUsdJmrQO-QK3Fooocju5sonIKM
