vim.api.nvim_create_user_command("NewFile", function(args)
	vim.cmd("enew")
	vim.cmd("%d")
	vim.cmd("w " .. args.args)
end, { nargs = 1, complete = "file" })

vim.api.nvim_create_user_command("WQ", "wq", {})
vim.api.nvim_create_user_command("Wq", "wq", {})
vim.api.nvim_create_user_command("W", "w", {})
vim.api.nvim_create_user_command("Qa", "qa", {})
vim.api.nvim_create_user_command("Q", "q", {})
